export const CREATE_TRADE = "CREATE_TRADE";
export const LOAD_SINGLE_TRADE = "LOAD_SINGLE_TRADE";
export const LOAD_ALL_TRADES_SUCCESS = "LOAD_ALL_TRADES_SUCCESS";
export const LOAD_ALL_MARGIN_LENDING_TRADES = "LOAD_ALL_MARGIN_LENDING_TRADES";
